development:
  adapter: mysql
  encoding: utf8
  database: brio_development
  username: root
  password: 
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: brio_test
  username: root
  password: 
  socket: /tmp/mysql.sock

staging:
  adapter: mysql
  encoding: utf8
  database: brio_development
  username: root
  password: LastHope